# Generated by Django 2.0.5 on 2018-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
