# Generated by Django 2.0.5 on 2018-05-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_manage', '0003_auto_20180525_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position_id',
            new_name='position',
        ),
    ]
