# Generated by Django 2.0.5 on 2018-05-30 08:39

import curd_manage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_manage', '0004_auto_20180529_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.FileField(upload_to=curd_manage.models.upload_avatar),
        ),
    ]
